### ISSUE TITLE
Usability enhancement

### ISSUE THREAD

**Issue by anniinakovalainen** [GispoCoding/GlobeBuilder#20]
The overall workflow with this plugin can go mainly in two ways: the user goes through all the sections and makes the selections and after that pushes the button "Add the globe to the map". When looking at this workflow, all the "Apply-like" buttons in the sections are confusing. But when thinking about the other workflow, which comes into play usually after the globe is added to the map, the user usually makes changes to the visuals or centering and needs the Apply buttons in different sections. So what to do? **I suggest that there is only one "Apply" or "Apply changes" button next to "Add the globe to the map/layout" buttons that are visible all the time when user is making changes in whatever section.** This way the first time user's workflow won't be like "Data sources, do I now push the apply button or what, okay now I pushed it and it appeared with wrong visualizations" and this happens with every section. If there is a button in a section, it gives the vibe it should be pressed before going to next section (this is what Windows thought us people).

I suggest the following usability changes to the plugin:

**Data sources _(optional)_**
- Insert "optional" so that new user understands from one glance that the globe can be added to own data.
- In this section, remove the button "Load data to map" - there should be only one "Apply changes" button next to the "Add the Globe to the Map/Layout" buttons.

**Projection**
- For some reason, this section is missing the heading. Image below.

![image](https://user-images.githubusercontent.com/51991990/128992362-6edaf65a-34e9-491a-89cd-d857d876e24a.png)

**Centering**
- Change "Center _to_ the current view".
- This selection would be more neat with a drop down menu. When you select for example coordinates, the input field 'Longitude, latitude' appears after that. Now there is so much stuff that at one glance it is not clear what is what.
- In this section too, remove the button "Center".

**Visualization**
- This is a bit more problematic section because of the optional data sources that can be visualized through this plugin.
- Remove "Colors" heading - no need.
- Move "Globe Layout background" to Layout section. It is confusing when there is visualization options for Layout in both sections.
- I would change the colors accordingly:
               Background
               **Halo (this is a heading)**
               Fill
               Line
               **Optional visualizations (this is heading)**
               Countries
               Graticules

**Layout**
- I'm not sure if this section is necessary, but maybe just leave it be, hehe. I myself don't touch this, I will do the layout visualizations in the Print Composer.

**Attributions**
- **Important! Move the buttons from below this section after the Layout section. These buttons are in the wrong place, one would think these have something to do with the attributions text (read more etc.) rather than them being key functions of the plugin.**

That's all folks! Awesome plugin all in all, I have been using it a lot lately.

**Comment by Joonalai** [comment]
Thank you for the proposal! I am sure this will be implemented in the near future.
