### ISSUE TITLE
Feature request: easier integration with map layout

### ISSUE THREAD

**Issue by tjukanovt** [GispoCoding/GlobeBuilder#7]
Most probably the plugin is used often as a locator map in the map layout window (as in the image below, taken from Wikipedia). Would it be possible to add a button that would open the globe dialog to the **map layout window**, where an user could just add a second map layout to the printed page. 

If someone has ideas from UI/UX perspective on how to implement this, comments are welcome.
![image](https://user-images.githubusercontent.com/13899537/73836541-2d05ef00-4818-11ea-9dc2-c44b7edf442d.png)

**Comment by Joonalai** [comment]
I think the main functionality is now added.
